/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_feuer_derp_MyGLRenderer */

#ifndef _Included_com_example_feuer_derp_MyGLRenderer
#define _Included_com_example_feuer_derp_MyGLRenderer
#ifdef __cplusplus
extern "C" {
#endif

void on_surface_created();
 
  void on_surface_changed(int w, int h);
 
void on_draw_frame();
  
/*
 * Class:     com_example_feuer_derp_MyGLRenderer
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_feuer_derp_MyGLRenderer_on_1surface_1created
(JNIEnv *, jclass) {
  on_surface_created();
}

/*
 * Class:     com_example_feuer_derp_MyGLRenderer
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_feuer_derp_MyGLRenderer_on_1surface_1changed
(JNIEnv *, jclass, jint w, jint h) {
  on_surface_changed(w, h);
}

/*
 * Class:     com_example_feuer_derp_MyGLRenderer
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_feuer_derp_MyGLRenderer_on_1draw_1frame
(JNIEnv *, jclass) {
  on_draw_frame();
}

#ifdef __cplusplus
}
#endif
#endif
